! compilation nvfortran -cudalib=cufft cufft1d_test.cuf
program cufft1dTest
    use cudafor
    use cufft
    implicit none
    
    integer, parameter :: n = 512
    real(8), parameter :: eps = 1d-14 ! accuracy
    
    ! Managed variables may be used in both host and device code
    complex(8), managed :: a(n), b(n) 
    
    real(8) x
    integer plan, ierr
    logical passing
    
    a = 1.0
    
    ierr = cufftPlan1D(plan,n,CUFFT_Z2Z, 1)
    ierr = ierr + cufftExecZ2Z(plan,a,b,CUFFT_FORWARD)
    ierr = ierr + cufftExecZ2Z(plan,b,b,CUFFT_INVERSE)
    ierr = ierr + cudaDeviceSynchronize()
    
    x = maxval(abs(a-b/(n)))
    write(*,*) 'Max error Z2Z: ', x
    
    passing = x .le. eps
    
    ierr = ierr + cufftDestroy(plan)
    print *,ierr
    
    passing = passing .and. (ierr .eq. 0)
    if (passing) then
        print *,"Test PASSED"
    else
        print *,"Test FAILED"
    endif
    
end program cufft1dTest
